<a href="https://colab.research.google.com/github/moshehaimlevi/numpy.repo/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import numpy as np
from IPython.display import display

############################## SECTION NUMBER 1 ##############################
num= np.arange(0, 10 +1)
display(num)
num1= np.arange(0.5, 5+ 0.1, 0.25)
display(num1)

############################## SECTION NUMBER 2 ##############################
print(np.zeros(10, dtype=int))

print(np.zeros((3, 4)))

############################## SECTION NUMBER 3 ##############################
print(np.linspace(2, 12, 5, dtype=int))

print(np.linspace(3, 9, 4, dtype=int))

############################## SECTION NUMBER 4 ##############################
np.random.seed(42)
randy = np.random.rand(2,4)
print(randy)

np.random.seed(42)
np.random.randint(10, 20, (3,3))









array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  ,
       3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[ 2  4  7  9 12]
[3 5 7 9]
[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]]


array([[16, 13, 17],
       [14, 16, 19],
       [12, 16, 17]])