<a href="https://colab.research.google.com/github/moshehaimlevi/numpy.repo/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from IPython.display import display

################ SECTION NUMBER 1 ################

num= np.arange(1, 17)
display(num)
num.resize(4, 4)
display(num)

################ SECTION NUMBER 2 ################

num1= np.arange(10, 50, 5)
display(num1)

reshape_num1=num1.reshape(2, 4)
display(reshape_num1)

################ SECTION NUMBER 3 ################
np.random.seed(23)
rand_array = np.random.randint(0, 100, (3, 3))
print(rand_array)
print('max', rand_array.max())  # max
print('min', rand_array.min())  # min
print('shape', rand_array.shape)

################ SECTION NUMBER 4 ################                  ###BONUS####

num2= np.arange(0, 20)
num2.resize(10,)

display(num2)
display(num2[:5])

jump2= np.arange(0, 20, 2)
display(jump2)

descnum2 = np.arange(0, 20)
display(descnum2 [::-1])

################ SECTION NUMBER 5 ################

np.random.seed(9)

rand_array2 = np.random.randint(1, 50, (4, 5))
display(rand_array2)
display(rand_array2[:2:4])









array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

array([10, 15, 20, 25, 30, 35, 40, 45])

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

[[83 40 73]
 [54 31 76]
 [91 39 90]]
max 91
min 31
shape (3, 3)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])