<a href="https://colab.research.google.com/github/moshehaimlevi/numpy.repo/blob/main/numpy3%2Bp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
from IPython.display import display

########################### SECTION NUMBER 1 ###########################

###################### SECTION A:
np.random.seed(80)
rand_array = np.random.randint(1, 100, [4, 4])
display(rand_array)
###################### SECTION B:

print('\nSUM axis=0 columns:\n', rand_array.sum(axis=0))
print('\nSUM axis=1 rows:   \n',rand_array.sum(axis=1))

###################### SECTION C:
print('\nAVG axis=0 columns:\n', rand_array.mean(axis=0))
print('\nAVG axis=1 rows:   \n',rand_array.mean(axis=1))

print('\nMIN axis=0 columns:\n', rand_array.mean(axis=0))
print('\nMIN axis=1 rows:   \n',rand_array.mean(axis=1))

print('\nMAX axis=0 columns:\n', rand_array.max(axis=0))
print('\nMAX axis=1 rows:   \n',rand_array.max(axis=1))






array([[48, 61, 39, 84],
       [11, 51,  4, 87],
       [24, 16, 82,  6],
       [65, 10, 93, 43]])


SUM axis=0 columns:
 [148 138 218 220]

SUM axis=1 rows:   
 [232 153 128 211]

AVG axis=0 columns:
 [37.  34.5 54.5 55. ]

AVG axis=1 rows:   
 [58.   38.25 32.   52.75]

MIN axis=0 columns:
 [37.  34.5 54.5 55. ]

MIN axis=1 rows:   
 [58.   38.25 32.   52.75]

MAX axis=0 columns:
 [65 61 93 87]

MAX axis=1 rows:   
 [84 87 82 93]


In [29]:
############# PANDAS ###############
########################### SECTION NUMBER 2 ###########################
import numpy as np
from IPython.display import display
import pandas as pd

new_games = {
"Final Fantasy VII Rebirth": 69.99,
"Astro Bot": 59.99,
"Star Wars Outlaws": 69.99,
"Silent Hill 2 Remake": 69.99,
"Elden Ring: Shadow of the Erdtree": 39.99,
"Dragon Age: The Veilguard": 69.99,
"Metaphor: ReFantazio": 59.99
}


games_dict = pd.Series(new_games)
print(games_dict)
print()
###################### SECTION A:

display('the retail price of Metaphor: ReFantazio is:', games_dict['Metaphor: ReFantazio'])
print()
###################### SECTION B:
print(games_dict.keys())
print()

###################### SECTION C:
display('the price in index 3 is',games_dict.iloc[3])
print()

###################### SECTION D:
print("value of all",games_dict.values.sum())
print()




Final Fantasy VII Rebirth            69.99
Astro Bot                            59.99
Star Wars Outlaws                    69.99
Silent Hill 2 Remake                 69.99
Elden Ring: Shadow of the Erdtree    39.99
Dragon Age: The Veilguard            69.99
Metaphor: ReFantazio                 59.99
dtype: float64



'the retail price of Metaphor: ReFantazio is:'

59.99


Index(['Final Fantasy VII Rebirth', 'Astro Bot', 'Star Wars Outlaws',
       'Silent Hill 2 Remake', 'Elden Ring: Shadow of the Erdtree',
       'Dragon Age: The Veilguard', 'Metaphor: ReFantazio'],
      dtype='object')



'the price in index 3 is'

69.99


value of all 439.93

